"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import { applyAction, initialDue, type Action } from "./statusEngine";
import type { Referral } from "./types";

// ---------------------------------------------------------------------------
// Create a new referral. The VOR- code is generated by the DB trigger.
// ---------------------------------------------------------------------------
export async function createReferral(form: {
  referring_provider_id: string;
  specialist_name?: string;
  specialty?: string;
  specialist_phone?: string;
  specialist_fax?: string;
}): Promise<{ ok: boolean; code?: string; error?: string }> {
  const supabase = createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "Not signed in." };

  const { data, error } = await supabase
    .from("referrals")
    .insert({
      referring_provider_id: form.referring_provider_id,
      specialist_name: form.specialist_name || null,
      specialty: form.specialty || null,
      specialist_phone: form.specialist_phone || null,
      specialist_fax: form.specialist_fax || null,
      appointment_state: "referral_created",
      document_state: "awaiting_appointment",
      next_action_due: initialDue(),
      last_action_at: new Date().toISOString(),
    })
    .select("id, code")
    .single();

  if (error) return { ok: false, error: error.message };

  // seed the history log with the creation event
  await supabase.from("status_history").insert({
    referral_id: data.id,
    track: "appointment",
    from_state: null,
    to_state: "referral_created",
    note_code: "created",
    changed_by: user.id,
  });

  revalidatePath("/tracking");
  revalidatePath("/todo");
  return { ok: true, code: data.code };
}

// ---------------------------------------------------------------------------
// Apply an action to a referral: compute the transition, update the row,
// and append the immutable history entry.
// ---------------------------------------------------------------------------
export async function performAction(
  referralId: string,
  action: Action,
  direction: "outbound" | "inbound" = "outbound"
): Promise<{ ok: boolean; error?: string; flag?: string }> {
  const supabase = createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "Not signed in." };

  const { data: current, error: readErr } = await supabase
    .from("referrals")
    .select("*")
    .eq("id", referralId)
    .single();
  if (readErr || !current) return { ok: false, error: readErr?.message ?? "Referral not found." };

  let result;
  try {
    result = applyAction(current as Referral, action);
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }

  const { log, flag, ...fields } = result;

  const { error: updErr } = await supabase.from("referrals").update(fields).eq("id", referralId);
  if (updErr) return { ok: false, error: updErr.message };

  const noteCode =
    direction === "inbound" && log.note_code ? `inbound_${log.note_code}` : log.note_code;

  const { error: logErr } = await supabase.from("status_history").insert({
    referral_id: referralId,
    track: log.track,
    from_state: log.from,
    to_state: log.to,
    note_code: noteCode,
    changed_by: user.id,
  });
  if (logErr) return { ok: false, error: logErr.message };

  revalidatePath("/tracking");
  revalidatePath(`/tracking/${current.code}`);
  revalidatePath("/todo");
  revalidatePath("/dashboard");
  return { ok: true, flag };
}

// ---------------------------------------------------------------------------
// Permanently remove a referral (admin only — also enforced by RLS).
// status_history rows cascade-delete with it.
// ---------------------------------------------------------------------------
export async function deleteReferral(
  referralId: string,
  confirmCode: string
): Promise<{ ok: boolean; error?: string }> {
  const supabase = createClient();

  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { ok: false, error: "Not signed in." };

  const { data: me } = await supabase.from("app_users").select("role").eq("id", user.id).single();
  if (me?.role !== "admin") return { ok: false, error: "Admin only." };

  const { data: referral, error: readErr } = await supabase
    .from("referrals")
    .select("id, code")
    .eq("id", referralId)
    .single();
  if (readErr || !referral) return { ok: false, error: "Referral not found." };
  if (referral.code !== confirmCode) return { ok: false, error: "Code confirmation didn't match." };

  const { error } = await supabase.from("referrals").delete().eq("id", referralId);
  if (error) return { ok: false, error: error.message };

  revalidatePath("/tracking");
  revalidatePath("/todo");
  revalidatePath("/dashboard");
  return { ok: true };
}

export async function signOut() {
  const supabase = createClient();
  await supabase.auth.signOut();
}
