"use server";

import { createClient } from "@/lib/supabase/server";
import { revalidatePath } from "next/cache";
import {
  applyAction,
  correctStatus as computeCorrection,
  initialDue,
  suggestDue,
  type Action,
  type Correction,
  type HistoryEvent,
} from "./statusEngine";
import {
  buildExisting,
  validateExisting,
  type ExistingReferralInput,
} from "./existingReferral";
import type { Referral } from "./types";

type Result = { ok: boolean; error?: string };

const CONFLICT_MESSAGE = "The referral changed since this page was loaded. Refresh and try again.";
const MRN_MAX_LENGTH = 32; // mirrors the mrn_format check in schema.sql

// Trim outer whitespace only — never coerce to a number (leading zeros matter).
function normalizeMrn(raw: string | undefined): { mrn?: string; error?: string } {
  const mrn = (raw ?? "").trim();
  if (!mrn) return { error: "MRN is required." };
  if (mrn.length > MRN_MAX_LENGTH) return { error: `MRN must be at most ${MRN_MAX_LENGTH} characters.` };
  return { mrn };
}

// Map a database error to a safe user message. Raw Postgres text can echo row
// values (including MRN), so it is logged server-side and never returned.
function dbError(context: string, error: { code?: string; message: string }): string {
  console.error(`[actions] ${context} failed`, error.code ?? "", error.message);
  if (error.code === "VT409") return CONFLICT_MESSAGE;
  if (error.code === "42501") return "Only admins can do this.";
  if (error.code === "P0002") return "Referral not found.";
  if (error.code === "23514" && error.message.includes("mrn_format")) return "MRN is invalid.";
  if (error.code === "23514" && error.message.includes("report_email")) return "That email address is invalid.";
  return "Could not save. Try again.";
}

async function requireAdmin() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { supabase, error: "Not signed in." };
  const { data: me } = await supabase.from("app_users").select("role, active").eq("id", user.id).maybeSingle();
  if (me?.role !== "admin" || !me.active) return { supabase, error: "Only admins can do this." };
  return { supabase, error: null };
}

type RpcEvent = {
  track: string;
  from_state: string | null;
  to_state: string;
  note_code: string;
  note_text: string | null;
  changed_at: string | null;
};

function toRpcEvents(
  events: (HistoryEvent & { note_text?: string | null; changed_at?: string })[],
  note?: string
): RpcEvent[] {
  return events.map((e, i) => ({
    track: e.track,
    from_state: e.from,
    to_state: e.to,
    note_code: e.note_code,
    // a typed note belongs to the first (primary) event of the action
    note_text: e.note_text ?? (i === 0 ? note?.trim() || null : null),
    changed_at: e.changed_at ?? null,
  }));
}

function revalidateReferral(code?: string) {
  revalidatePath("/tracking");
  if (code) revalidatePath(`/tracking/${code}`);
  revalidatePath("/todo");
  revalidatePath("/dashboard");
  revalidatePath("/reports/weekly");
}

// Load the row, refuse if it changed since the caller's page loaded it.
async function loadCurrent(
  supabase: ReturnType<typeof createClient>,
  referralId: string,
  expectedUpdatedAt: string
): Promise<{ current?: Referral; error?: string }> {
  const { data, error } = await supabase.from("referrals").select("*").eq("id", referralId).maybeSingle();
  if (error) return { error: dbError("load referral", error) };
  if (!data) return { error: "Referral not found." };
  if (new Date(data.updated_at).getTime() !== new Date(expectedUpdatedAt).getTime()) {
    return { error: CONFLICT_MESSAGE };
  }
  return { current: data as Referral };
}

// Write fields + history rows in one transaction (apply_referral_change RPC).
// The RPC re-checks updated_at under a row lock, so two admins acting at once
// cannot both succeed.
async function commit(
  supabase: ReturnType<typeof createClient>,
  current: Referral,
  fields: Record<string, unknown>,
  events: RpcEvent[],
  context: string
): Promise<Result> {
  const { error } = await supabase.rpc("apply_referral_change", {
    p_referral_id: current.id,
    p_expected_updated_at: current.updated_at,
    p_fields: fields,
    p_events: events,
  });
  if (error) return { ok: false, error: dbError(context, error) };
  revalidateReferral(current.code);
  return { ok: true };
}

// ---------------------------------------------------------------------------
// Create a new referral. The VOR- code is generated by the DB trigger.
// ---------------------------------------------------------------------------
export async function createReferral(form: {
  mrn: string;
  referring_provider_id: string;
  specialist_name?: string;
  specialty?: string;
  specialist_phone?: string;
  specialist_fax?: string;
  referral_date?: string;
}): Promise<{ ok: boolean; code?: string; error?: string }> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };

  const { mrn, error: mrnErr } = normalizeMrn(form.mrn);
  if (mrnErr) return { ok: false, error: mrnErr };

  const referralDate = form.referral_date ?? new Date().toISOString();
  if (new Date(referralDate).getTime() > Date.now()) return { ok: false, error: "Open date cannot be in the future." };

  const { data, error } = await supabase.rpc("create_referral", {
    p_fields: {
      mrn,
      referring_provider_id: form.referring_provider_id,
      specialist_name: form.specialist_name || null,
      specialty: form.specialty || null,
      specialist_phone: form.specialist_phone || null,
      specialist_fax: form.specialist_fax || null,
      appointment_state: "referral_created",
      document_state: "awaiting_appointment",
      referral_date: referralDate,
      next_action_due: initialDue(new Date(referralDate)),
      last_action_at: referralDate,
    },
    p_events: [
      { track: "appointment", from_state: null, to_state: "referral_created", note_code: "created", note_text: null, changed_at: referralDate },
    ],
  });
  if (error) return { ok: false, error: dbError("create referral", error) };

  revalidateReferral();
  return { ok: true, code: (data as Referral).code };
}

// ---------------------------------------------------------------------------
// Add a referral that is already in progress, at its real current stage.
// ---------------------------------------------------------------------------
export async function createExistingReferral(
  input: ExistingReferralInput
): Promise<{ ok: boolean; code?: string; error?: string }> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };

  const { mrn, error: mrnErr } = normalizeMrn(input.mrn);
  if (mrnErr) return { ok: false, error: mrnErr };
  const clean = { ...input, mrn: mrn as string };

  const problem = validateExisting(clean);
  if (problem) return { ok: false, error: problem };

  const { fields, events } = buildExisting(clean);
  const { data, error } = await supabase.rpc("create_referral", {
    p_fields: fields,
    p_events: toRpcEvents(events),
  });
  if (error) return { ok: false, error: dbError("create existing referral", error) };

  revalidateReferral();
  return { ok: true, code: (data as Referral).code };
}

// ---------------------------------------------------------------------------
// Apply a workflow action: validate against the CURRENT state, compute the
// transition, and write the row + every history row in one transaction.
//   expectedUpdatedAt: the referral's updated_at as the caller's page saw it.
// ---------------------------------------------------------------------------
export async function performAction(
  referralId: string,
  expectedUpdatedAt: string,
  action: Action,
  direction: "outbound" | "inbound" = "outbound",
  note?: string
): Promise<{ ok: boolean; error?: string; flag?: string }> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };

  const { current, error: loadErr } = await loadCurrent(supabase, referralId, expectedUpdatedAt);
  if (!current) return { ok: false, error: loadErr };

  let result;
  try {
    result = applyAction(current, action);
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }

  // Direction marks a phone contact the patient initiated. Only the primary
  // event is the call; follow-on events (e.g. records now due) are not calls.
  const events = result.events.map((e, i) =>
    direction === "inbound" && i === 0 && e.track !== "meta" ? { ...e, note_code: `inbound_${e.note_code}` } : e
  );

  const res = await commit(supabase, current, { ...result.fields }, toRpcEvents(events, note), "perform action");
  return res.ok ? { ok: true, flag: result.flag } : res;
}

// ---------------------------------------------------------------------------
// Correct status — admin fix for a wrong entry. Reason is mandatory and is
// stored on every correction row. History is appended, never rewritten.
// ---------------------------------------------------------------------------
export async function correctStatus(
  referralId: string,
  expectedUpdatedAt: string,
  correction: Correction,
  reason: string
): Promise<Result> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };
  if (!reason.trim()) return { ok: false, error: "A reason is required." };

  const { current, error: loadErr } = await loadCurrent(supabase, referralId, expectedUpdatedAt);
  if (!current) return { ok: false, error: loadErr };

  let result;
  try {
    result = computeCorrection(current, correction);
  } catch (e) {
    return { ok: false, error: (e as Error).message };
  }

  const events = toRpcEvents(result.events).map((e) => ({ ...e, note_text: reason.trim() }));
  return commit(supabase, current, { ...result.fields }, events, "correct status");
}

// ---------------------------------------------------------------------------
// Edit descriptive details. Never touches workflow state; the history row lists
// WHICH fields changed, never their values (keeps MRN out of timeline text).
// ---------------------------------------------------------------------------
export async function editReferralDetails(
  referralId: string,
  expectedUpdatedAt: string,
  form: {
    mrn: string;
    referring_provider_id: string;
    referral_date: string;
    specialist_name: string;
    specialty: string;
    specialist_phone: string;
    specialist_fax: string;
    appointment_slot: string | null;
  }
): Promise<Result> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };

  const { mrn, error: mrnErr } = normalizeMrn(form.mrn);
  if (mrnErr) return { ok: false, error: mrnErr };
  if (!form.referring_provider_id) return { ok: false, error: "Pick the internal provider." };
  if (isNaN(Date.parse(form.referral_date))) return { ok: false, error: "Enter a valid open date." };
  if (new Date(form.referral_date).getTime() > Date.now()) return { ok: false, error: "Open date cannot be in the future." };

  const { current, error: loadErr } = await loadCurrent(supabase, referralId, expectedUpdatedAt);
  if (!current) return { ok: false, error: loadErr };

  const slotEditable = [
    "appointment_scheduled", "appointment_rescheduled", "appointment_confirmed", "appointment_completed",
  ].includes(current.appointment_state);
  if (slotEditable && (!form.appointment_slot || isNaN(Date.parse(form.appointment_slot)))) {
    return { ok: false, error: "This status needs an appointment date." };
  }

  const next: Record<string, string | null> = {
    mrn: mrn as string,
    referring_provider_id: form.referring_provider_id,
    referral_date: new Date(form.referral_date).toISOString(),
    specialist_name: form.specialist_name.trim() || null,
    specialty: form.specialty.trim() || null,
    specialist_phone: form.specialist_phone.trim() || null,
    specialist_fax: form.specialist_fax.trim() || null,
  };
  if (slotEditable) next.appointment_slot = new Date(form.appointment_slot as string).toISOString();

  const LABELS: Record<string, string> = {
    mrn: "MRN",
    referring_provider_id: "Internal provider",
    referral_date: "Open date",
    specialist_name: "Specialist",
    specialty: "Specialty",
    specialist_phone: "Specialist phone",
    specialist_fax: "Specialist fax",
    appointment_slot: "Appointment date",
  };
  const TIME_FIELDS = new Set(["referral_date", "appointment_slot"]);
  const cur = current as unknown as Record<string, string | null>;
  const changed = Object.keys(next).filter((k) =>
    TIME_FIELDS.has(k)
      ? (cur[k] ? new Date(cur[k] as string).getTime() : null) !== (next[k] ? new Date(next[k] as string).getTime() : null)
      : (cur[k] ?? null) !== (next[k] ?? null)
  );
  if (changed.length === 0) return { ok: true };

  const fields: Record<string, unknown> = {};
  for (const k of changed) fields[k] = next[k];

  // A moved appointment moves its pre/post-visit call with it.
  if (changed.includes("appointment_slot") && current.appointment_state !== "appointment_completed") {
    fields.next_action_due = suggestDue(
      { ...current, appointment_slot: next.appointment_slot },
      new Date()
    );
  }

  const events: RpcEvent[] = [
    {
      track: "meta",
      from_state: null,
      to_state: "details_edited",
      note_code: "details_edited",
      note_text: `Changed: ${changed.map((k) => LABELS[k]).join(", ")}`,
      changed_at: null,
    },
  ];
  return commit(supabase, current, fields, events, "edit details");
}

// ---------------------------------------------------------------------------
// Provider report email (weekly report recipient — copied by hand, never sent).
// ---------------------------------------------------------------------------
export async function updateProviderEmail(providerId: string, email: string): Promise<Result> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };
  const value = email.trim() || null;
  if (value && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value)) return { ok: false, error: "That email address is invalid." };

  const { error } = await supabase.from("referring_providers").update({ report_email: value }).eq("id", providerId);
  if (error) return { ok: false, error: dbError("update provider email", error) };
  revalidatePath("/reports/weekly");
  return { ok: true };
}

// ---------------------------------------------------------------------------
// Permanently remove a referral (admin only — also enforced by RLS).
// status_history rows cascade-delete with it.
// ---------------------------------------------------------------------------
export async function deleteReferral(
  referralId: string,
  confirmCode: string
): Promise<Result> {
  const { supabase, error: authErr } = await requireAdmin();
  if (authErr) return { ok: false, error: authErr };

  const { data: referral, error: readErr } = await supabase
    .from("referrals")
    .select("id, code")
    .eq("id", referralId)
    .maybeSingle();
  if (readErr) return { ok: false, error: dbError("load referral", readErr) };
  if (!referral) return { ok: false, error: "Referral not found." };
  if (referral.code !== confirmCode) return { ok: false, error: "Code confirmation didn't match." };

  const { error } = await supabase.from("referrals").delete().eq("id", referralId);
  if (error) return { ok: false, error: dbError("delete referral", error) };

  revalidateReferral();
  return { ok: true };
}

export async function signOut() {
  const supabase = createClient();
  await supabase.auth.signOut();
}
